name: API Test

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    permissions:
      contents: write

    strategy:
      matrix:
        python-version: [3.10.6]

    steps:
      - uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test App
        run: |
          coverage run -m pytest

      - name: Coveralls
        run: |
          coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ vars.COVERALLS_REPO_TOKEN }}
