name: API Test

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app/

    permissions:
      contents: write

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ../test_requirements.txt

      - name: Test App
        run: coverage run -m pytest

      - name: Generate Coverage Badge
        run: coverage-badge -o coverage.svg

      - name: Coverage badge to repo
        run: cp /home/runner/work/Language_Identifier/Language_Identifier/coverage.svg ../
