name: API Test

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    permissions:
      contents: write

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test_requirements.txt

      - name: Test App
        run: |
          cd app/
          coverage run -m pytest
          coverage-badge -o coverage_2.svg

      - name: Commit badge
        run: |
          git config --global user.email "ignatiuskisekka@gmail.com"
          git config --global user.name "Ignatius K"
          git add coverage.svg
          git commit -m "Add: coverage badge"
          git remote set-url origin https://${{ secrets.TOKEN }}@github.com/${{ github.repository }}
          git push
          
